[package]
name = "regex"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]

[[test]]
name = "regex-ha-test"
path = "../test/src/regex_ha_test.rs"
harness = true
